name: Deploy Container
on: push

jobs:
  deploy_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |

          docker image build . -t test
          docker run -d -p 8080:80 test:latest
