name: Deploy Container
on: push

jobs:
  deploy_docker:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          docker login
          docker container run -d -p 8080:80 test:1
